In [1]:
%pwd

'd:\\work\\git\\ece5995'

In [9]:
import pandas as pd
from pandas import DataFrame
from gps_pkg import gps as gp

In [3]:
df_in = pd.read_csv('test.csv')

In [4]:
df_in

                time_str  longitude   latitude
0   2015-03-29T17:15:46Z -83.115963  42.476571
1   2015-03-29T17:15:48Z -83.116533  42.476482
2   2015-03-29T17:15:50Z -83.117145  42.476389
3   2015-03-29T17:15:52Z -83.117725  42.476361
4   2015-03-29T17:15:54Z -83.118322  42.476318
5   2015-03-29T17:15:56Z -83.118961  42.476306
6   2015-03-29T17:15:58Z -83.119639  42.476276
7   2015-03-29T17:16:00Z -83.120335  42.476270
8   2015-03-29T17:16:02Z -83.121097  42.476338
9   2015-03-29T17:16:04Z -83.121792  42.476223
10  2015-03-29T17:16:06Z -83.122519  42.476191
11  2015-03-29T17:16:08Z -83.123172  42.476311
12  2015-03-29T17:16:10Z -83.123968  42.476299
13  2015-03-29T17:16:12Z -83.124735  42.476258
14  2015-03-29T17:16:14Z -83.125567  42.476221
15  2015-03-29T17:16:16Z -83.126318  42.476204
16  2015-03-29T17:16:18Z -83.127108  42.476168
17  2015-03-29T17:16:20Z -83.127909  42.476139
18  2015-03-29T17:16:22Z -83.128706  42.476121
19  2015-03-29T17:16:24Z -83.129515  42.476141
20  2015-03-29T17:16:26Z -83.130297  42.476145
21  2015-03-29T17:16:28Z -83.131149  42.476098
22  2015-03-29T17:16:30Z -83.131968  42.476044
23  2015-03-29T17:16:32Z -83.132759  42.476018
24  2015-03-29T17:16:34Z -83.133528  42.476007
25  2015-03-29T17:16:36Z -83.134243  42.475974
26  2015-03-29T17:16:38Z -83.134913  42.475948
27  2015-03-29T17:16:40Z -83.135585  42.475933
28  2015-03-29T17:16:42Z -83.136245  42.475887
29  2015-03-29T17:16:44Z -83.136911  42.475802
..                   ...        ...        ...
62  2015-03-29T17:17:49Z -83.162008  42.474477
63  2015-03-29T17:17:51Z -83.162776  42.474525
64  2015-03-29T17:17:53Z -83.163503  42.474647
65  2015-03-29T17:17:55Z -83.164265  42.474712
66  2015-03-29T17:17:57Z -83.165020  42.474834
67  2015-03-29T17:17:59Z -83.165782  42.474886
68  2015-03-29T17:18:01Z -83.166588  42.474938
69  2015-03-29T17:18:03Z -83.167376  42.475014
70  2015-03-29T17:18:05Z -83.168150  42.474982
71  2015-03-29T17:18:07Z -83.168947  42.474957
72  2015-03-29T17:18:09Z -83.169751  42.474929
73  2015-03-29T17:18:11Z -83.170531  42.474882
74  2015-03-29T17:18:13Z -83.171329  42.474878
75  2015-03-29T17:18:15Z -83.172111  42.474888
76  2015-03-29T17:18:17Z -83.172885  42.474879
77  2015-03-29T17:18:19Z -83.173694  42.474864
78  2015-03-29T17:18:21Z -83.174434  42.474786
79  2015-03-29T17:18:23Z -83.175207  42.474842
80  2015-03-29T17:18:25Z -83.175989  42.474870
81  2015-03-29T17:18:27Z -83.176778  42.474833
82  2015-03-29T17:18:29Z -83.177598  42.474790
83  2015-03-29T17:18:31Z -83.178388  42.474752
84  2015-03-29T17:18:33Z -83.179177  42.474738
85  2015-03-29T17:18:35Z -83.179972  42.474732
86  2015-03-29T17:18:37Z -83.180774  42.474714
87  2015-03-29T17:18:39Z -83.181601  42.474688
88  2015-03-29T17:18:41Z -83.182410  42.474654
89  2015-03-29T17:18:43Z -83.183170  42.474633
90  2015-03-29T17:18:45Z -83.183955  42.474598
91  2015-03-29T17:18:47Z -83.184737  42.474589

[92 rows x 3 columns]

In [6]:
df_in['latitude']

0     42.476571
1     42.476482
2     42.476389
3     42.476361
4     42.476318
5     42.476306
6     42.476276
7     42.476270
8     42.476338
9     42.476223
10    42.476191
11    42.476311
12    42.476299
13    42.476258
14    42.476221
15    42.476204
16    42.476168
17    42.476139
18    42.476121
19    42.476141
20    42.476145
21    42.476098
22    42.476044
23    42.476018
24    42.476007
25    42.475974
26    42.475948
27    42.475933
28    42.475887
29    42.475802
        ...
62    42.474477
63    42.474525
64    42.474647
65    42.474712
66    42.474834
67    42.474886
68    42.474938
69    42.475014
70    42.474982
71    42.474957
72    42.474929
73    42.474882
74    42.474878
75    42.474888
76    42.474879
77    42.474864
78    42.474786
79    42.474842
80    42.474870
81    42.474833
82    42.474790
83    42.474752
84    42.474738
85    42.474732
86    42.474714
87    42.474688
88    42.474654
89    42.474633
90    42.474598
91    42.474589
Name: latitude, Length: 92, dtype: float64

In [7]:
df_in['latitude'][0]

42.476571

In [8]:
max(df_in['latitude'])

42.476571

In [10]:
gp.GPSDistance(df_in['latitude'][0],df_in['longitude'][0],df_in['latitude'][1],df_in['longitude'][1])

47.78306783186812

In [11]:
df_in

                time_str  longitude   latitude
0   2015-03-29T17:15:46Z -83.115963  42.476571
1   2015-03-29T17:15:48Z -83.116533  42.476482
2   2015-03-29T17:15:50Z -83.117145  42.476389
3   2015-03-29T17:15:52Z -83.117725  42.476361
4   2015-03-29T17:15:54Z -83.118322  42.476318
5   2015-03-29T17:15:56Z -83.118961  42.476306
6   2015-03-29T17:15:58Z -83.119639  42.476276
7   2015-03-29T17:16:00Z -83.120335  42.476270
8   2015-03-29T17:16:02Z -83.121097  42.476338
9   2015-03-29T17:16:04Z -83.121792  42.476223
10  2015-03-29T17:16:06Z -83.122519  42.476191
11  2015-03-29T17:16:08Z -83.123172  42.476311
12  2015-03-29T17:16:10Z -83.123968  42.476299
13  2015-03-29T17:16:12Z -83.124735  42.476258
14  2015-03-29T17:16:14Z -83.125567  42.476221
15  2015-03-29T17:16:16Z -83.126318  42.476204
16  2015-03-29T17:16:18Z -83.127108  42.476168
17  2015-03-29T17:16:20Z -83.127909  42.476139
18  2015-03-29T17:16:22Z -83.128706  42.476121
19  2015-03-29T17:16:24Z -83.129515  42.476141
20  2015-03-29T17:16:26Z -83.130297  42.476145
21  2015-03-29T17:16:28Z -83.131149  42.476098
22  2015-03-29T17:16:30Z -83.131968  42.476044
23  2015-03-29T17:16:32Z -83.132759  42.476018
24  2015-03-29T17:16:34Z -83.133528  42.476007
25  2015-03-29T17:16:36Z -83.134243  42.475974
26  2015-03-29T17:16:38Z -83.134913  42.475948
27  2015-03-29T17:16:40Z -83.135585  42.475933
28  2015-03-29T17:16:42Z -83.136245  42.475887
29  2015-03-29T17:16:44Z -83.136911  42.475802
..                   ...        ...        ...
62  2015-03-29T17:17:49Z -83.162008  42.474477
63  2015-03-29T17:17:51Z -83.162776  42.474525
64  2015-03-29T17:17:53Z -83.163503  42.474647
65  2015-03-29T17:17:55Z -83.164265  42.474712
66  2015-03-29T17:17:57Z -83.165020  42.474834
67  2015-03-29T17:17:59Z -83.165782  42.474886
68  2015-03-29T17:18:01Z -83.166588  42.474938
69  2015-03-29T17:18:03Z -83.167376  42.475014
70  2015-03-29T17:18:05Z -83.168150  42.474982
71  2015-03-29T17:18:07Z -83.168947  42.474957
72  2015-03-29T17:18:09Z -83.169751  42.474929
73  2015-03-29T17:18:11Z -83.170531  42.474882
74  2015-03-29T17:18:13Z -83.171329  42.474878
75  2015-03-29T17:18:15Z -83.172111  42.474888
76  2015-03-29T17:18:17Z -83.172885  42.474879
77  2015-03-29T17:18:19Z -83.173694  42.474864
78  2015-03-29T17:18:21Z -83.174434  42.474786
79  2015-03-29T17:18:23Z -83.175207  42.474842
80  2015-03-29T17:18:25Z -83.175989  42.474870
81  2015-03-29T17:18:27Z -83.176778  42.474833
82  2015-03-29T17:18:29Z -83.177598  42.474790
83  2015-03-29T17:18:31Z -83.178388  42.474752
84  2015-03-29T17:18:33Z -83.179177  42.474738
85  2015-03-29T17:18:35Z -83.179972  42.474732
86  2015-03-29T17:18:37Z -83.180774  42.474714
87  2015-03-29T17:18:39Z -83.181601  42.474688
88  2015-03-29T17:18:41Z -83.182410  42.474654
89  2015-03-29T17:18:43Z -83.183170  42.474633
90  2015-03-29T17:18:45Z -83.183955  42.474598
91  2015-03-29T17:18:47Z -83.184737  42.474589

[92 rows x 3 columns]

In [19]:
df_in['distance']=0.0

In [20]:
df_in

                time_str  longitude   latitude  distance
0   2015-03-29T17:15:46Z -83.115963  42.476571       0.0
1   2015-03-29T17:15:48Z -83.116533  42.476482       0.0
2   2015-03-29T17:15:50Z -83.117145  42.476389       0.0
3   2015-03-29T17:15:52Z -83.117725  42.476361       0.0
4   2015-03-29T17:15:54Z -83.118322  42.476318       0.0
5   2015-03-29T17:15:56Z -83.118961  42.476306       0.0
6   2015-03-29T17:15:58Z -83.119639  42.476276       0.0
7   2015-03-29T17:16:00Z -83.120335  42.476270       0.0
8   2015-03-29T17:16:02Z -83.121097  42.476338       0.0
9   2015-03-29T17:16:04Z -83.121792  42.476223       0.0
10  2015-03-29T17:16:06Z -83.122519  42.476191       0.0
11  2015-03-29T17:16:08Z -83.123172  42.476311       0.0
12  2015-03-29T17:16:10Z -83.123968  42.476299       0.0
13  2015-03-29T17:16:12Z -83.124735  42.476258       0.0
14  2015-03-29T17:16:14Z -83.125567  42.476221       0.0
15  2015-03-29T17:16:16Z -83.126318  42.476204       0.0
16  2015-03-29T17:16:18Z -83.127108  42.476168       0.0
17  2015-03-29T17:16:20Z -83.127909  42.476139       0.0
18  2015-03-29T17:16:22Z -83.128706  42.476121       0.0
19  2015-03-29T17:16:24Z -83.129515  42.476141       0.0
20  2015-03-29T17:16:26Z -83.130297  42.476145       0.0
21  2015-03-29T17:16:28Z -83.131149  42.476098       0.0
22  2015-03-29T17:16:30Z -83.131968  42.476044       0.0
23  2015-03-29T17:16:32Z -83.132759  42.476018       0.0
24  2015-03-29T17:16:34Z -83.133528  42.476007       0.0
25  2015-03-29T17:16:36Z -83.134243  42.475974       0.0
26  2015-03-29T17:16:38Z -83.134913  42.475948       0.0
27  2015-03-29T17:16:40Z -83.135585  42.475933       0.0
28  2015-03-29T17:16:42Z -83.136245  42.475887       0.0
29  2015-03-29T17:16:44Z -83.136911  42.475802       0.0
..                   ...        ...        ...       ...
62  2015-03-29T17:17:49Z -83.162008  42.474477       0.0
63  2015-03-29T17:17:51Z -83.162776  42.474525       0.0
64  2015-03-29T17:17:53Z -83.163503  42.474647       0.0
65  2015-03-29T17:17:55Z -83.164265  42.474712       0.0
66  2015-03-29T17:17:57Z -83.165020  42.474834       0.0
67  2015-03-29T17:17:59Z -83.165782  42.474886       0.0
68  2015-03-29T17:18:01Z -83.166588  42.474938       0.0
69  2015-03-29T17:18:03Z -83.167376  42.475014       0.0
70  2015-03-29T17:18:05Z -83.168150  42.474982       0.0
71  2015-03-29T17:18:07Z -83.168947  42.474957       0.0
72  2015-03-29T17:18:09Z -83.169751  42.474929       0.0
73  2015-03-29T17:18:11Z -83.170531  42.474882       0.0
74  2015-03-29T17:18:13Z -83.171329  42.474878       0.0
75  2015-03-29T17:18:15Z -83.172111  42.474888       0.0
76  2015-03-29T17:18:17Z -83.172885  42.474879       0.0
77  2015-03-29T17:18:19Z -83.173694  42.474864       0.0
78  2015-03-29T17:18:21Z -83.174434  42.474786       0.0
79  2015-03-29T17:18:23Z -83.175207  42.474842       0.0
80  2015-03-29T17:18:25Z -83.175989  42.474870       0.0
81  2015-03-29T17:18:27Z -83.176778  42.474833       0.0
82  2015-03-29T17:18:29Z -83.177598  42.474790       0.0
83  2015-03-29T17:18:31Z -83.178388  42.474752       0.0
84  2015-03-29T17:18:33Z -83.179177  42.474738       0.0
85  2015-03-29T17:18:35Z -83.179972  42.474732       0.0
86  2015-03-29T17:18:37Z -83.180774  42.474714       0.0
87  2015-03-29T17:18:39Z -83.181601  42.474688       0.0
88  2015-03-29T17:18:41Z -83.182410  42.474654       0.0
89  2015-03-29T17:18:43Z -83.183170  42.474633       0.0
90  2015-03-29T17:18:45Z -83.183955  42.474598       0.0
91  2015-03-29T17:18:47Z -83.184737  42.474589       0.0

[92 rows x 4 columns]

In [21]:
for i in range(len(df_in)):
    if i > 0:
        lat1_deg   = df_in['latitude'][i-1] 
        long1_deg  = df_in['longitude'][i-1]
        lat2_deg   = df_in['latitude'][i]
        long2_deg  = df_in['longitude'][i] 
        df_in['distance'][i] = gp.GPSDistance(lat1_deg, long1_deg, lat2_deg, long2_deg)
    #df_in['distance'][i] = gp.GPSDistance()

C:\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [22]:
df_in

                time_str  longitude   latitude   distance
0   2015-03-29T17:15:46Z -83.115963  42.476571   0.000000
1   2015-03-29T17:15:48Z -83.116533  42.476482  47.783068
2   2015-03-29T17:15:50Z -83.117145  42.476389  51.245807
3   2015-03-29T17:15:52Z -83.117725  42.476361  47.668960
4   2015-03-29T17:15:54Z -83.118322  42.476318  49.194350
5   2015-03-29T17:15:56Z -83.118961  42.476306  52.423070
6   2015-03-29T17:15:58Z -83.119639  42.476276  55.704575
7   2015-03-29T17:16:00Z -83.120335  42.476270  57.084659
8   2015-03-29T17:16:02Z -83.121097  42.476338  62.949405
9   2015-03-29T17:16:04Z -83.121792  42.476223  58.415611
10  2015-03-29T17:16:06Z -83.122519  42.476191  59.729356
11  2015-03-29T17:16:08Z -83.123172  42.476311  55.191507
12  2015-03-29T17:16:10Z -83.123968  42.476299  65.295612
13  2015-03-29T17:16:12Z -83.124735  42.476258  63.068627
14  2015-03-29T17:16:14Z -83.125567  42.476221  68.358524
15  2015-03-29T17:16:16Z -83.126318  42.476204  61.620541
16  2015-03-29T17:16:18Z -83.127108  42.476168  64.913672
17  2015-03-29T17:16:20Z -83.127909  42.476139  65.771288
18  2015-03-29T17:16:22Z -83.128706  42.476121  65.394745
19  2015-03-29T17:16:24Z -83.129515  42.476141  66.385607
20  2015-03-29T17:16:26Z -83.130297  42.476145  64.135592
21  2015-03-29T17:16:28Z -83.131149  42.476098  70.070129
22  2015-03-29T17:16:30Z -83.131968  42.476044  67.436379
23  2015-03-29T17:16:32Z -83.132759  42.476018  64.936611
24  2015-03-29T17:16:34Z -83.133528  42.476007  63.079773
25  2015-03-29T17:16:36Z -83.134243  42.475974  58.753944
26  2015-03-29T17:16:38Z -83.134913  42.475948  55.024731
27  2015-03-29T17:16:40Z -83.135585  42.475933  55.138001
28  2015-03-29T17:16:42Z -83.136245  42.475887  54.369711
29  2015-03-29T17:16:44Z -83.136911  42.475802  55.432419
..                   ...        ...        ...        ...
62  2015-03-29T17:17:49Z -83.162008  42.474477  63.319033
63  2015-03-29T17:17:51Z -83.162776  42.474525  63.213223
64  2015-03-29T17:17:53Z -83.163503  42.474647  61.148613
65  2015-03-29T17:17:55Z -83.164265  42.474712  62.911775
66  2015-03-29T17:17:57Z -83.165020  42.474834  63.389700
67  2015-03-29T17:17:59Z -83.165782  42.474886  62.761962
68  2015-03-29T17:18:01Z -83.166588  42.474938  66.356004
69  2015-03-29T17:18:03Z -83.167376  42.475014  65.177421
70  2015-03-29T17:18:05Z -83.168150  42.474982  63.578694
71  2015-03-29T17:18:07Z -83.168947  42.474957  65.424473
72  2015-03-29T17:18:09Z -83.169751  42.474929  66.012978
73  2015-03-29T17:18:11Z -83.170531  42.474882  64.184406
74  2015-03-29T17:18:13Z -83.171329  42.474878  65.449024
75  2015-03-29T17:18:15Z -83.172111  42.474888  64.144866
76  2015-03-29T17:18:17Z -83.172885  42.474879  63.487018
77  2015-03-29T17:18:19Z -83.173694  42.474864  66.370604
78  2015-03-29T17:18:21Z -83.174434  42.474786  61.307294
79  2015-03-29T17:18:23Z -83.175207  42.474842  63.702257
80  2015-03-29T17:18:25Z -83.175989  42.474870  64.210905
81  2015-03-29T17:18:27Z -83.176778  42.474833  64.840114
82  2015-03-29T17:18:29Z -83.177598  42.474790  67.421676
83  2015-03-29T17:18:31Z -83.178388  42.474752  64.929116
84  2015-03-29T17:18:33Z -83.179177  42.474738  64.728227
85  2015-03-29T17:18:35Z -83.179972  42.474732  65.205071
86  2015-03-29T17:18:37Z -83.180774  42.474714  65.806256
87  2015-03-29T17:18:39Z -83.181601  42.474688  67.887799
88  2015-03-29T17:18:41Z -83.182410  42.474654  66.457523
89  2015-03-29T17:18:43Z -83.183170  42.474633  62.374947
90  2015-03-29T17:18:45Z -83.183955  42.474598  64.499121
91  2015-03-29T17:18:47Z -83.184737  42.474589  64.143426

[92 rows x 4 columns]

In [23]:
sum(df_in['distance'])

5666.048030865478